[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydata"
version = "0.0.1"
description = "Datacenter of econ data"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    { name = "Marc de la Barrera", email = "marc.delabarrera@gmail.com" }
]
dependencies = []

[project.urls]
"Homepage" = "Homepage = "https://github.com/marcdelabarrera/pydata"

[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]
