[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydata"
version = "0.0.1"
description = "Datacenter of econ data"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    { name = "Marc de la Barrera", email = "marc.delabarrera@gmail.com" }
]
dependencies = []

[project.urls]
"Homepage" = "na"

[tool.setuptools.packages.find]
where = ["."]